Benefits/Controllers/ClienteController.cs
using Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Repository;
using System;
using System.Net;
using System.Threading.Tasks;

namespace Benefits.Controllers
{
    public class ClienteController : Controller
    {

        private readonly EmpresaClienteDAO _empresaClienteDAO;
        private readonly ClienteDAO _clienteDAO;
        private readonly EmpresaDAO _empresaDAO;
        private readonly UsuarioDAO _usuarioDAO;
        private readonly UserManager<UsuarioLogado> _userManager;
        private readonly SignInManager<UsuarioLogado> _signInManager;

        public ClienteController(EmpresaClienteDAO empresaClienteDAO, EmpresaDAO empresaDAO, ClienteDAO clienteDAO, UsuarioDAO usuarioDAO, UserManager<UsuarioLogado> userManager, SignInManager<UsuarioLogado> signInManager)
        {
            _empresaClienteDAO = empresaClienteDAO;
            _empresaDAO = empresaDAO;
            _clienteDAO = clienteDAO;
            _userManager = userManager;
            _signInManager = signInManager;
            _usuarioDAO = usuarioDAO;
        }

        #region Navigation Views Crud
        public async Task<IActionResult> Index(Cliente cliente)
        {
            UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
            return View(_clienteDAO.BuscarPorEmail(userLogado.Email));
        }
        public IActionResult Cadastrar()
        {
            Cliente cliente = new Cliente();
            if (TempData["Endereco"] != null)
            {
                string resultado = TempData["Endereco"].ToString();
                Endereco endereco = JsonConvert.DeserializeObject<Endereco>(resultado);
                cliente.Endereco = endereco;
            }
            return View(cliente);
        }
        public IActionResult Editar(int id)
        {
            return View(_clienteDAO.BuscarPorId(id));
        }
        public IActionResult Excluir(int id)
        {
            return View(_clienteDAO.BuscarPorId(id));
        }
        #endregion

        #region Consumo de API
        [HttpPost]
        public IActionResult BuscarCep(Cliente cliente)
        {
            string url = "http://apps.widenet.com.br/busca-cep/api/cep/" + cliente.Endereco.Code + ".json";
            WebClient client = new WebClient();
            TempData["Endereco"] = client.DownloadString(url);
            return RedirectToAction(nameof(Cadastrar));
        }
        #endregion

        #region Navigation Views

        public IActionResult Parceiros()
        {
            return View();
        }
        public async Task<IActionResult> Beneficios()
        {
            UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
            return View(_empresaClienteDAO.ListarTodosBeneficiosPorEmail(userLogado.Email));
        }
        #endregion

        #region Crud Actions
        //[HttpPost]
        //public IActionResult Cadastrar(Cliente cliente)
        //{
        //TODO: validar campos
        //TODO: Não deixar cadastrar clientes iguais
        //if (_clienteDAO.Cadastrar(cliente))
        //{
        //return RedirectToAction("Index", cliente);
        //}
        //return View(cliente);
        //}
        [HttpPost]
        public IActionResult Editar(Cliente cliente)
        {
            _clienteDAO.Editar(cliente);
            return RedirectToAction("Index", cliente);
        }
        [HttpPost]
        public IActionResult Excluir(Cliente cliente)
        {
            _clienteDAO.Remover(_clienteDAO.BuscarPorId(cliente.ClienteId));
            return RedirectToAction("Index", cliente);
        }
        #endregion

        #region EMRPESAS

        public IActionResult Empresas()
        {
            return View(_empresaDAO.ListarTodos());
        }


        public IActionResult EmpresaParceria(int? id)
        {
            TempData["id"] = id;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EmpresaParceria(EmpresaCliente empresaCliente)
        {
            try
            {
                int idEmpresa = Convert.ToInt32(TempData["id"].ToString());
                UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
                empresaCliente.Cliente = _clienteDAO.BuscarPorEmail(userLogado.Email);
                _empresaClienteDAO.Cadastrar(empresaCliente);
                return RedirectToAction("empresas");
            }
            catch (System.Exception)
            {
                return View(empresaCliente);
                throw;
            }
        }

        public async Task<IActionResult> EmpresaParceriasMinhas()
        {
            UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
            return View(_empresaClienteDAO.ListarMinhasEmpresas(userLogado.Email));
        }

        public IActionResult EmpresaRemoverParceria(int? id)
        {
            TempData["id"] = id;
            return View();
        }

        // TESTAR FUNÇAO =-==========================================
        [HttpPost]
        public async Task<IActionResult> EmpresaRemoverParceria()
        {

            UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
            _empresaClienteDAO.RemoverClienteEmailEEmpresaId(userLogado.Email, Convert.ToInt32(TempData["id"].ToString()));
            return RedirectToAction("index");
        }

        public IActionResult EmpresaBeneficios(int? id)
        {
            return View(_clienteDAO.RetornarBeneficiosDeEmpresaId(id));
        }

        public IActionResult EmpresaDetails(int? id)
        {
            return View(_empresaDAO.BuscarPorId(id));
        }

        public IActionResult EmpresaClienteDetails(int? id)
        {
            return View(_empresaClienteDAO.BuscarPorId(id));
        }

















        #endregion

        [HttpPost]
        public async Task<IActionResult> Cadastrar(Cliente cliente, string Senha, string ConfirmacaoSenha)
        {
            if (cliente == null)
            {
                return View();
            }
            if (Senha == null || ConfirmacaoSenha == null)
            {
                return View(cliente);
            }
            if (!(Senha.Equals(ConfirmacaoSenha)))
            {
                return View(cliente);
            }
            if (ModelState.IsValid)
            {
                //Criar um objeto do UsuarioLogado e passar                 
                //obrigatoriamente o Email e UserName
                Usuario usuario = new Usuario();
                UsuarioLogado usuarioLogado = new UsuarioLogado
                {
                    Email = cliente.Email,
                    UserName = cliente.Email
                };

                usuario.Email = cliente.Email;
                usuario.Senha = Senha;
                usuario.ConfirmacaoSenha = ConfirmacaoSenha;
                usuario.Tipo = false;//[Tipo: false == Cliente]
                usuario.Identificador = cliente.Identificador;
                if (_usuarioDAO.Cadastrar(usuario))
                {
                    IdentityResult result = await _userManager.
                    CreateAsync(usuarioLogado, usuario.Senha);
                    //Testar o resultado do cadastro
                    if (result.Succeeded)
                    {
                        //Logar o usuário no sistema
                        await _signInManager.SignInAsync(usuarioLogado,
                            isPersistent: false);
                        if (_clienteDAO.Cadastrar(cliente))
                        {
                            return RedirectToAction("Index", cliente);
                        }
                        ModelState.AddModelError("", "Este e-mail já está sendo utilizado!");
                    }
                    AdicionarErros(result);
                }
                //Cadastra o usuário na tabela do Identity
            }
            return View(cliente);
        }
        private void AdicionarErros(IdentityResult result)
        {
            foreach (var erro in result.Errors)
            {
                ModelState.AddModelError
                    ("", erro.Description);
            }
        }


    }

}

Benefits/Controllers/EmpresaController.cs
using Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Repository;
using System;
using System.Threading.Tasks;

//PEGAR USUARIO ATUAL
//UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
//string email = userLogado.Email;
//beneficio.Empresa = _empresaDAO.BuscarPorEmail(email);

namespace Benefits.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly EmpresaEmpresaDAO _empresaEmpresaDAO;
        private readonly EmpresaClienteDAO _empresaClienteDAO;
        private readonly BeneficioDAO _beneficioDAO;
        private readonly EmpresaDAO _empresaDAO;
        private readonly UsuarioDAO _usuarioDAO;
        private readonly UserManager<UsuarioLogado> _userManager;
        private readonly SignInManager<UsuarioLogado> _signInManager;

        public EmpresaController(EmpresaEmpresaDAO empresaEmpresaDAO, EmpresaClienteDAO empresaClienteDAO, BeneficioDAO beneficioDAO, EmpresaDAO empresaDAO, UsuarioDAO usuarioDAO, UserManager<UsuarioLogado> userManager, SignInManager<UsuarioLogado> signInManager)
        {
            _empresaClienteDAO = empresaClienteDAO;
            _empresaEmpresaDAO = empresaEmpresaDAO;
            _beneficioDAO = beneficioDAO;
            _empresaDAO = empresaDAO;
            _usuarioDAO = usuarioDAO;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        #region Navigation Views Crud
        public async Task<IActionResult> Index()
        {
            UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
            return View(_empresaDAO.BuscarPorEmail(userLogado.Email));
        }
        public IActionResult Cadastrar()
        {
            return View();
        }


        public IActionResult Parceiros()
        {
            return View();
        }


        public IActionResult Editar(int id)
        {
            return View(_empresaDAO.BuscarPorId(id));
        }
        public IActionResult Excluir(int id)
        {
            return View(_empresaDAO.BuscarPorId(id));
        }
        #endregion

        #region Crud Actions
        [HttpPost]
        public async Task<IActionResult> Cadastrar(Empresa empresa, string Senha, string ConfirmacaoSenha)
        {
            if (empresa == null)
            {
                return View();
            }
            if (Senha == null || Senha == "")
            {
                return View(empresa);
            }
            if (ConfirmacaoSenha == null || ConfirmacaoSenha == "")
            {
                return View(empresa);
            }
            if (!(Senha.Equals(ConfirmacaoSenha)))
            {
                return View(empresa);
            }
            if (ModelState.IsValid)
            {
                Usuario usuario = new Usuario();
                UsuarioLogado usuarioLogado = new UsuarioLogado
                {
                    Email = empresa.Email,
                    UserName = empresa.Email
                };
                usuario.Email = empresa.Email;
                usuario.Senha = Senha;
                usuario.ConfirmacaoSenha = ConfirmacaoSenha;
                usuario.Tipo = true;//[Tipo: true == Empresa]
                usuario.Identificador = empresa.Identificador;
                if (_usuarioDAO.Cadastrar(usuario))
                {
                    IdentityResult result = await _userManager.
                    CreateAsync(usuarioLogado, usuario.Senha);
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(usuarioLogado,
                            isPersistent: false);
                        if (_empresaDAO.Cadastrar(empresa))
                        {
                            return RedirectToAction("Index", empresa);
                        }
                        ModelState.AddModelError("", "Este e-mail já está sendo utilizado!");
                    }
                    AdicionarErros(result);
                }
            }
            return View(empresa);
        }

        private void AdicionarErros(IdentityResult result)
        {
            foreach (var erro in result.Errors)
            {
                ModelState.AddModelError
                    ("", erro.Description);
            }
        }

        [HttpPost]
        public IActionResult Editar(Empresa empresa)
        {
            _empresaDAO.Editar(empresa);
            return RedirectToAction("Index", empresa);
        }
        [HttpPost]
        public IActionResult Excluir(Empresa empresa)
        {
            _empresaDAO.Remover(_empresaDAO.BuscarPorId(empresa.EmpresaId));
            return RedirectToAction("Index", empresa.EmpresaId);
        }

        #endregion

        #region  EMPRESA CLIENTE
        //public IActionResult Clientes()
        //{
        //    return View(_empresaClienteDAO.ListarTodos());
        //}
        //public IActionResult ClientesCreate()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult ClientesCreate(Beneficio beneficio)
        //{

        //        //return RedirectToAction("BeneficiosView", beneficio);

        //    return View(beneficio);
        //}

        #endregion

        #region BENEFICIOS 
        public async Task<IActionResult> Beneficios()
        {
            UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
            string email = userLogado.Email;
            var x = _empresaDAO.BuscarPorEmail(email);
            return View(_beneficioDAO.ListarBeneficiosEmpresa(x.Email));
        }
        public IActionResult BeneficiosCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BeneficiosCreate(Beneficio beneficio)
        {
            if (_beneficioDAO.ValidaPorNome(beneficio))
            {
                UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
                beneficio.Empresa = _empresaDAO.BuscarPorEmail(userLogado.Email);
                _beneficioDAO.Cadastrar(beneficio);
                return RedirectToAction("BeneficiosDetails", beneficio);
            }

            return View(beneficio);
        }
        public IActionResult BeneficiosEdit(int? id)
        {
            return View(_beneficioDAO.BuscarPorId(id));
        }
        [HttpPost]
        public IActionResult BeneficiosEdit(Beneficio beneficio)
        {
            _beneficioDAO.Editar(beneficio);
            return RedirectToAction("BeneficiosView", beneficio);
        }
        public IActionResult BeneficiosDetails(Beneficio beneficio)
        {
            return View(beneficio);
        }

        #endregion

        #region EMRPESAS

        public IActionResult Empresas()
        {
            return View(_empresaDAO.ListarTodos());
        }

        public IActionResult EmpresaEmpresaDetails(int? id)
        {
            return View(_empresaEmpresaDAO.BuscarPorId(id));
        }

        public IActionResult EmpresaParceiro(int? id)
        {
            TempData["empresaId"] = id;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EmpresaParceiro(EmpresaEmpresa empresaEmpresa)
        {
            UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
            empresaEmpresa.EmpresaUm = _empresaDAO.BuscarPorEmail(userLogado.Email);
            empresaEmpresa.EmpresaDois = _empresaDAO.BuscarPorId(Convert.ToInt32(TempData["empresaId"].ToString()));
            _empresaEmpresaDAO.Cadastrar(empresaEmpresa);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EmpresaEmpresaParceirosMeu()
        {
            UsuarioLogado userLogado = await _userManager.GetUserAsync(User);
            return View(_empresaEmpresaDAO.ListarTodosComEmail(userLogado.Email));
        }

        public IActionResult EmpresaBeneficiosParceiro(int? id)
        {
            return View(_beneficioDAO.ListarTodosEmpresaId(id));
        }


        #endregion
    }
}

Benefits/Views/Shared/_ClienteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Benefits</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" asp-controller="Cliente" asp-action="Index"><img src="~/images/Icons/home-24px.svg"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Cliente" asp-action="Index">Início <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cliente" asp-action="Empresas">Empresas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cliente" asp-action="EmpresaParceriasMinhas">Empresas parceiras</a>
                </li>
                @*<li class="nav-item">
            <a class="nav-link" asp-controller="Cliente" asp-action="Parceiros">Parceiros</a>
        </li>*@
                @*<li class="nav-item">
            <a class="nav-link" asp-controller="Cliente" asp-action="Beneficios">Meus Benefícios</a>
        </li>*@
                <li class="nav-item">
                    <a class="btn btn-dark" asp-controller="Usuario" asp-action="Logout">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container p-4">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Benefits</p>
        </footer>
    </div>
</body>
</html>

Benefits/Views/Shared/_EmpresaLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Benefits</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" asp-controller="Empresa" asp-action="Index"><img src="~/images/Icons/home-24px.svg"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                @*<li class="nav-item active">
            <a class="nav-link" asp-controller="Empresa" asp-action="Index">Início<span class="sr-only">(current)</span></a>
        </li>*@
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Empresa" asp-action="Empresas">Empresas<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Empresa" asp-action="EmpresaEmpresaParceirosMeu">Parceiros<span class="sr-only">(current)</span></a>
                </li>
                @*<li class="nav-item active">
            <a class="nav-link" asp-controller="Empresa" asp-action="Clientes">Clientes<span class="sr-only">(current)</span></a>
        </li>*@
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Empresa" asp-action="Beneficios">Benefícios<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-dark" asp-controller="Usuario" asp-action="Logout">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container p-4">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Benefits</p>
        </footer>
    </div>
</body>
</html>

Benefits/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Benefits - Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container p-4">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Benefits</p>
        </footer>
    </div>
</body>
</html>